angular.
    module('calendarApp',[
	'ngRoute',
	'calendarCtrls'
    ]).
    config(['$routeProvider',
	    function($routeProvider){
		$routeProvider.
		    when('/',{
			templateUrl:'partials/index.html',
			controller:'indexCtrl'
		    }).
		    when('/calendar/',{
			templateUrl:'partials/calendar.html',
			controller:'CalendarCtrl'
		    }).
		    when('/calendar/:region',{
			templateUrl:'partials/calendar.html',
			controller:'CalendarCtrl'
		    }).
		    when('/article/',{
			templateUrl:'partials/article.html',
			controller:'ArticleCtrl'
		    }).
		    when('/article/:id',{
			templateUrl:'partials/article.html',
			controller:'ArticleCtrl'
		    }).
		    otherwise({
			retidectTo:'/'
		    });
	    }]);
